test-scsi-rules: check prerquisites on startup

diff --git a/test-scsi-rules b/test-scsi-rules
--- a/test-scsi-rules
+++ b/test-scsi-rules
@@ -28,6 +28,16 @@ SG3_RULES="55-scsi-sg3_id.rules"
 ALL_RULES="$UDEV_RULES $SG3_RULES"
 TEST_RULES="10-test-scsi.rules"
 
+check_reqs() {
+    local p
+    for p in systemctl udevadm curl tar sha1sum sg_inq; do
+	type $p &>/dev/null || {
+	    echo "program \"$p\" not found, please install it first" >&2
+	    exit 1
+	}
+    done
+}
+
 fetch_rules() {
     local f r
     pushd "$RULESD" >/dev/null
@@ -82,6 +92,7 @@ do_test() {
 
 [[ -d "$RULESD" ]] || mkdir "$RULESD"
 
+check_reqs
 check_etc_rulesd
 fetch_rules
 
